[package]
name = "audio-matcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
itertools = "0.11"
minimp3 = "0.5"
mp3-duration = "0.1"
fftconvolve = "0.1"
realfft = "3.3"
ndarray = "0.15"
find_peaks = "0.1"
pad = "0.1"
threadpool = "1.8"
clap = { version="4.3", features=["derive"]}
text_io = "0.1"
thiserror = "1.0"
derive_builder = "0.12"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
