[package]
name = "audio-matcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
minimp3 = "0.5"
mp3-duration = "0.1"
fftconvolve = "0.1"
ndarray = "0.15"
find_peaks = "0.1"
pad = "0.1"
threadpool = "1.8"
clap = { version="4.3", features=["derive"]}
